pipeline {
    agent any
    tools {
        // Define the Maven installation from Jenkins configuration
        maven 'Maven'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your SCM
                echo '1. Checkout Source code from SVN'
                checkout scm
            }
        }
        stage('Stop Apache') {
            steps {
                    echo '2. Stopping Apache Services'
                    bat 'net stop Tomcat9'
            }
        }
        
        
        stage('Build') {
            steps {
                // Build the Maven project using Windows batch command                
                dir('payroll') {
                    echo '3. Building Maven Project'
                    bat 'mvn clean package'
                }

            }
        }
        
        stage('Test') {
            steps {
                // Run tests (if any) using Windows batch command
                dir('payroll') {
                    echo '4. Testing Maven Project'
                    bat 'mvn test'
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                dir('payroll') {
                    echo '5. Deploying War file on Tomcat Server'
                    bat 'copy target\\*.war "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\"'
                }
            }
        }
        stage('Start Apache') {
            steps {
                   echo '6. Starting Apache Services Again'
                   bat 'net start Tomcat9'
            }
        }
    }
}
