pipeline {
    agent any
    tools {
        // Define the Maven installation from Jenkins configuration
        maven 'Maven'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your SCM
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                // Build the Maven project using Windows batch command                
                dir('payroll') {
                    bat 'mvn clean package'
                }

            }
        }
        
        stage('Test') {
            steps {
                // Run tests (if any) using Windows batch command
                dir('payroll') {
                    bat 'mvn test'
                }
            }
        }

         stage('Stop Apache') {
            steps {
                    echo 'Stoping Apache ..................... '
                    bat 'net stop Tomcat9'
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                dir('payroll') {
                    bat 'copy target\\*.war "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\"'
                }
            }
        }
        stage('Start Apache') {
            steps {
                   echo 'Starting Apache ..................... '
                   bat 'net start Tomcat9'
            }
        }
    }
}
